---
- name: check bundler install
  shell: /home/ec2-user/.rbenv/shims/bundler --version
  register: check_bundler_installed
  changed_when: no
  ignore_errors: yes

#- name: check bundler install
#  shell: bash -lc "bundler version | grep {{ bundler_version }}"
#  register: check_bundler_installed
#  changed_when: no
#  ignore_errors: yes

- name: install bundler
  gem: 
    name: bundler
    version: "{{ bundler_version }}"
    executable: /home/ec2-user/.rbenv/shims/gem
    user_install: no
  when: check_bundler_installed is failed

